# Generated by Django 4.1.7 on 2023-03-31 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('garagem', '0008_modelo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Modelo',
        ),
        migrations.AddField(
            model_name='veiculo',
            name='modelo',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
