# Generated by Django 4.1.7 on 2023-05-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("garagem", "0009_delete_modelo_veiculo_modelo"),
    ]

    operations = [
        migrations.CreateModel(
            name="Modelo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("descricao", models.CharField(max_length=100)),
            ],
            options={
                "verbose_name_plural": "Modelos",
            },
        ),
        migrations.AlterModelOptions(
            name="cor",
            options={"verbose_name_plural": "Cores"},
        ),
    ]
